# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assoc', models.CharField(blank=True, help_text='Administering association', max_length=150)),
                ('comp', models.CharField(help_text='Competition name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('m', 'Men'), ('w', 'Women')], max_length=2)),
                ('team_list', models.FileField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('team_name', 'division')]),
        ),
    ]
